name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: "9.1"
          custom_script: |
            sudo chown -R 1000:1000 .
            make

      - name: Revert permissions
        if: always()
        run: sudo chown -R 1001:116 .
